### ISSUE TITLE
Nofollow

### ISSUE THREAD

**Issue by captn3m0** [hackercouch/hackercouch#29]
I personally don't like using `rel=nofollow`, but wanted to hear others opinion on the matter.

**Comment by ppaeps** [comment]
On 2015-11-30 21:30:41 (+0530), Nemo notifications@github.com wrote:

> I personally don't like using `rel=nofollow`, but wanted to hear 
> others opinion on the matter.

What problem would be solved by preventing automated clients from 
following links?

Presumably links in couch descriptions can be trusted because they've 
been added as patches and merged by (more or less ;)) trustworthy 
collaborators.

## 

Philip Paeps
Senior Reality Engineer
Ministry of Information

**Comment by captn3m0** [comment]
Sounds good. We just need to make sure that the couch descriptions and links are not too spammy. Maybe even hook it up to a spam filter? There are free spam detection APIs, and we can just run the couches through that and fail the build if needed.

**Comment by simison** [comment]
Sounds something you'd want invest time when/if this actually/ becomes an issue.

**Comment by captn3m0** [comment]
Yeah. I've filed #35 on how to improve tests. Closing this for now, since nofollow is clearly not needed.
